package com.yoku.server.fw.authentication.session;

import java.util.List;

/**
 * Stores users session related information into the application memory.
 */
public class UserContext {
	/**
	 * Indirected Id for actual MerchantId/NinjaId/CustomerId. This value will
	 * be different for different actual Ids across sessions.
	 */
	private String indirectedId;
	/**
	 * Actual value for MerchantId/NinjaId/CustomerId.
	 */
	private String id;
	/**
	 * The unique device identifier that will act as an identifier for the
	 * session and the user.
	 */
	private String deviceId;
	/**
	 * Authentication tokens generated by the system for user validation. This
	 * token would be updated after every NON-GET request.
	 */
	private String authToken;

	/**
	 * Authorization Role level for the logged in user.
	 */
	private String authorizationRole;

	/**
	 * @return the indirectedId
	 */
	public String getIndirectedId() {
		return indirectedId;
	}

	/**
	 * @param indirectedId
	 *            the indirectedId to set
	 */
	public void setIndirectedId(String indirectedId) {
		this.indirectedId = indirectedId;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the deviceId
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * @param deviceId
	 *            the deviceId to set
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	

	/**
	 * @return the authorizationRole
	 */
	public String getAuthorizationRole() {
		return authorizationRole;
	}

	/**
	 * @param authorizationRole
	 *            the authorizationRole to set
	 */
	public void setAuthorizationRole(String authorizationRole) {
		this.authorizationRole = authorizationRole;
	}

	/**
	 * @return the authToken
	 */
	public String getAuthToken() {
		return authToken;
	}

	/**
	 * @param authToken the authToken to set
	 */
	public void setAuthToken(String authToken) {
		this.authToken = authToken;
	}

	/** (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "UserContext [indirectedId=" + indirectedId + ", id=" + id + ", deviceId=" + deviceId + ", authToken="
				+ authToken + ", authorizationRole=" + authorizationRole + "]";
	}

	

}
