package com.yoku.server.framework.entity.merchant;

import java.sql.Date;

import com.yoku.server.framework.entity.core.IEntity;

public class OnboardMerchant implements IEntity {

	/**
	 * Generated Serial Version UID.
	 */
	private static final long serialVersionUID = -8506572939554159199L;

	/**
	 * Merchant OnBoard Registration Number generated by the application.
	 */
	private String registration_no;
	
	/**
	 * Merchant Name : First Name + Last Name
	 */
	private String merchant_name;
	/**
	 * Outlet specialization.
	 */
	private String specialization;
//	/**
//	 * Outlet Address details.
//	 */
//	private AddressDTO address;
//	/**
//	 * Merchant contact details.
//	 */
//	private ContactDTO contact;
	/**
	 * Introduced to Yoku by.
	 */
	private String referred_by;
	/**
	 * Date and TIme of application.
	 */
	private final Date applied_on = new Date(System.currentTimeMillis());
	/**
	 * @return the specialization
	 */
	public String getSpecialization() {
		return specialization;
	}
	/**
	 * @param specialization the specialization to set
	 */
	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}
//	/**
//	 * @return the address
//	 */
//	public AddressDTO getAddress() {
//		return address;
//	}
//	/**
//	 * @param address the address to set
//	 */
//	public void setAddress(AddressDTO address) {
//		this.address = address;
//	}
//	/**
//	 * @return the contact
//	 */
//	public ContactDTO getContact() {
//		return contact;
//	}
//	/**
//	 * @param contact the contact to set
//	 */
//	public void setContact(ContactDTO contact) {
//		this.contact = contact;
//	}
	/**
	 * @return the referredBy
	 */
	public String getReferredBy() {
		return referred_by;
	}
	/**
	 * @param referredBy the referredBy to set
	 */
	public void setReferredBy(String referredBy) {
		this.referred_by = referredBy;
	}
	/**
	 * @return the appliedOn
	 */
	public Date getAppliedOn() {
		return applied_on;
	}
	/**
	 * @return the registrationNumber
	 */
	public String getRegistrationNumber() {
		return registration_no;
	}
	/**
	 * @param registrationNumber the registrationNumber to set
	 */
	public void setRegistrationNumber(String registrationNumber) {
		this.registration_no = registrationNumber;
	}
	/**
	 * @return the merchant_name
	 */
	public String getMerchant_name() {
		return merchant_name;
	}
	/**
	 * @param merchant_name the merchant_name to set
	 */
	public void setMerchant_name(String merchant_name) {
		this.merchant_name = merchant_name;
	}
	
	


	
}
